${INC_GLOBAL}

[[chains]]
id = "coreum-mainnet-1"
${INC_COREUM_MAINNET_1}
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain name
    ['transfer', 'channel-6'],  # axelar
    ['transfer', 'channel-20'], # bandchain
    ['transfer', 'channel-9'],  # cosmoshub
    ['transfer', 'channel-24'], # dydx
    ['transfer', 'channel-8'],  # evmos
    ['transfer', 'channel-7'],  # gravitybridge
    ['transfer', 'channel-18'], # kava
    ['transfer', 'channel-17'], # kujira
    ['transfer', 'channel-19'], # noble
    ['transfer', 'channel-2'],  # osmosis
    ['transfer', 'channel-25'], # secret
]

[[chains]]
id = "osmosis-1"
${INC_OSMOSIS_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-2188'], # coreum
]

[[chains]]
id = "cosmoshub-4"
${INC_COSMOSHUB_4}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-660'], # coreum
]

[[chains]]
id = "axelar-dojo-1"
${INC_AXELAR_DOJO_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-120'], # coreum
]

[[chains]]
id = "evmos_9001-2"
${INC_EVMOS_9001_2}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-87'], # coreum
]

[[chains]]
id = "gravity-bridge-3"
${INC_GRAVITY_BRIDGE_3}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-142'], # coreum
]

[[chains]]
id = "kava_2222-10"
${INC_KAVA_2222_10}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-142'], # coreum
]

[[chains]]
id = "secret-4"
${INC_SECRET_4}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-101'], # coreum
]

[[chains]]
id = "noble-1"
${INC_NOBLE_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-49'], # coreum
]

[[chains]]
id = "kaiyo-1"
${INC_KAIYO_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-122'],
]

[[chains]]
id = "laozi-mainnet"
${INC_LAOZI_MAINNET}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-159'],
]

[[chains]]
id = "dydx-mainnet-1"
${INC_DYDX_MAINNET_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-14'], # coreum
]
