[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 0
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = "migaloo-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_whitewhale:8000'
grpc_addr = 'http://tasks.lb_whitewhale:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_whitewhale:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "migaloo"
key_name = "migaloo"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 1000000
max_gas = 5000000
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 3000000
max_grpc_decoding_size = 33554432
clock_drift = "500s"
max_block_time = "10s"
trusting_period = '336hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.34'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.4, denom = 'uwhale' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain_id
    ['transfer', 'channel-49'], # axelar-dojo-1
    ['transfer', 'channel-53'], # axelar-dojo-1
    ['transfer', 'channel-10'], # chihuahua-1
    ['transfer', 'channel-27'], # neutron-1
    ['transfer', 'channel-48'], # kava_2222-10
    ['transfer', 'channel-69'], # stargaze-1
    ['transfer', 'channel-56'], # umee-1
]

[[chains]]
id = "axelar-dojo-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_axelar:8000'
grpc_addr = 'http://tasks.lb_axelar:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_axelar:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "axelar"
key_name = "axelar"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 1000000
max_gas = 4000000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 1800000
max_grpc_decoding_size = 33554432
clock_drift = "50s"
max_block_time = "10s"
trusting_period = '112hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.34'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0075, denom = 'uaxl' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-112'],
    ['transfer', 'channel-121'],
]

[[chains]]
id = "chihuahua-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_chihuahua:8000'
grpc_addr = 'http://tasks.lb_chihuahua:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_chihuahua:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "chihuahua"
key_name = "chihuahua"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000000
max_gas = 1000000000
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 1000000
max_grpc_decoding_size = 33554432
clock_drift = "15s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.1, denom = 'uhuahua' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-39'],
]

[[chains]]
id = "neutron-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_neutron:8000'
grpc_addr = 'http://tasks.lb_neutron:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_neutron:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "neutron"
key_name = "neutron"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 1000000
gas_multiplier = 1.2
max_msg_num = 20
max_tx_size = 2097152
max_grpc_decoding_size = 33554432
clock_drift = "15s"
max_block_time = "10s"
trusting_period = '13days'
ccv_consumer_chain = false
#ccv_consumer_chain = true
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.6, denom = 'untrn' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-4'],
]

[[chains]]
id = "kava_2222-10"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_kava:8000'
grpc_addr = 'http://tasks.lb_kava:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_kava:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "kava"
key_name = "kava"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas =  10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '14days'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.34'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.0025, denom = 'ukava' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-120'],
]

[[chains]]
id = "stargaze-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_stargaze:8000'
grpc_addr = 'http://tasks.lb_stargaze:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_stargaze:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "stars"
key_name = "stargaze"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas = 1000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1000000
max_grpc_decoding_size = 33554432
clock_drift = "15s"
max_block_time = "10s"
trusting_period = '224hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.34'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 1, denom = 'ustars' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-269'],
]

[[chains]]
id = "umee-1"
type = "CosmosSdk"
rpc_addr = 'http://tasks.lb_umee:8000'
grpc_addr = 'http://tasks.lb_umee:8003'
event_source = { mode = 'push', url = 'ws://tasks.lb_umee:8000/websocket', batch_delay = '500ms' }
rpc_timeout = "30s"
trusted_node = false
account_prefix = "umee"
key_name = "umee"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 300000
max_gas =  10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 2097152
max_grpc_decoding_size = 33554432
clock_drift = "40s"
max_block_time = "10s"
trusting_period = '216hours'
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
compat_mode = '0.37'
trust_threshold = { numerator = '1', denominator = '3' }
gas_price = { price = 0.1, denom = 'uumee' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-104'],
]
