${INC_GLOBAL}

[[chains]]
id = "banksy-testnet-5"
${INC_BANKSY_TESTNET_5}
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain_id
    ['transfer', 'channel-44'], # osmo-test-5
]

[chains.packet_filter.min_fees]

[[chains]]
id = "osmo-test-5"
${INC_OSMO_TEST_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-7758'],
]
