${INC_GLOBAL}

[[chains]]
id = "injective-1"
${INC_INJECTIVE_1}
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain name
    ['transfer', 'channel-177'],  # neutron
]

[[chains]]
id = "neutron-1"
${INC_NEUTRON_1}

[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-60'],
]