${INC_GLOBAL}

[[chains]]
id = "kava_2222-10"
${INC_KAVA_2222_10}
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain name
    ["transfer", "channel-140"], # celestia
    ["transfer", "channel-0"],   # cosmoshub-4
    ["transfer", "channel-137"], # dydx-mainnet-1
    ["transfer", "channel-136"], # neutron-1
    ["transfer", "channel-139"], # noble-1
    ["transfer", "channel-1"],   # osmosis-1
    ["transfer", "channel-138"], # phoenix-1 (terra2)
]

[[chains]]
id = "celestia"
${INC_CELESTIA}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-13"],
]

[[chains]]
id = "noble-1"
${INC_NOBLE_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-37"],
]

[[chains]]
id = "dydx-mainnet-1"
${INC_DYDX_MAINNET_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-7"],
]

[[chains]]
id = "neutron-1"
${INC_NEUTRON_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-36"],
]

[[chains]]
id = "phoenix-1"
${INC_PHOENIX_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-272"],
]

[[chains]]
id = "cosmoshub-4"
${INC_COSMOSHUB_4}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-277"],
]

[[chains]]
id = "osmosis-1"
${INC_OSMOSIS_1}
[chains.packet_filter]
policy = "allow"
list = [
   ["transfer", "channel-143"],
]
