${INC_GLOBAL}

[[chains]]
id = "pacific-1"
${INC_PACIFIC_1}
[chains.packet_filter]
policy = "allow"
list = [
    # sort by chain name
    ["transfer", "channel-2"],  # axelar
    ['transfer', 'channel-47'], # coreum (move from coreum hub to)
    ["transfer", "channel-1"],  # cosmoshub
    ["transfer", "channel-0"],  # osmosis
    ["transfer", "channel-3"],  # terra2
]

[[chains]]
id = "axelar-dojo-1"
${INC_AXELAR_DOJO_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-103"], # sei
]

[[chains]]
id = "coreum-mainnet-1"
${INC_COREUM_MAINNET_1}
[chains.packet_filter]
policy = "allow"
list = [
    ['transfer', 'channel-26'], # sei
]

[[chains]]
id = "cosmoshub-4"
${INC_COSMOSHUB_4}
[chains.packet_filter]
policy = "allow"
list = [
     ["transfer", "channel-584"], # sei
]

[[chains]]
id = "osmosis-1"
${INC_OSMOSIS_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-782"], # sei
]

[[chains]]
id = "phoenix-1"
${INC_PHOENIX_1}
[chains.packet_filter]
policy = "allow"
list = [
    ["transfer", "channel-158"], # sei
]