${INC_GLOBAL}

[[chains]]
id = 'migaloo-1'
${INC_MIGALOO_1}
[chains.packet_filter]
policy = 'allow'
list = [
 ['transfer', 'channel-60'], # noble
]

[[chains]]
id = 'noble-1'
${INC_NOBLE_1}
[chains.packet_filter]
policy = 'allow'
list = [
 ['transfer','channel-14'], # migaloo
]

